application: droidyballthefuzzy
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:                                                                      
- name: jinja2                                                                  
  version: latest 

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /images
  static_dir: static/images
- url: /stylesheets
  static_dir: static/stylesheets
- url: /scripts 
  static_dir: scripts/
- url: /lib
  static_dir: lib/
- url: /todo/.*
  script: src.main.app
- url: /todo
  script: src.main.app
- url: /.*
  script: src.main.app