application: droidyballthefuzzy
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:                                                                      
- name: jinja2                                                                  
  version: latest 

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /images
  static_dir: static/images
  mime_type: image/jpeg
- url: /stylesheets
  static_dir: static/stylesheets
- url: /todo/.*
  script: src.main.app
  login: admin
- url: /todo
  script: scr.main.app
  login: admin